### ISSUE TITLE
Need to update Bower

### ISSUE THREAD

**Issue by edheltzel** [RainyDayMedia/flux#7]
- [x] update Neat
- [x] update Bourbon
- [x] update Normalize SCSS

**Comment by Toddses** [comment]
bah just drop bower and use NPM/Yarn.

**Comment by edheltzel** [comment]
Yarn really that better? I know it beings the dependencies local but that's the all I know about Yarn at the moment.




On Mon, Dec 19, 2016 at 9:13 AM, Todd Miller <notifications@github.com> wrote:
bah just drop bower and use NPM/Yarn.
